build:
    maxIssues: 0
    excludeCorrectable: false

config:
    validation: true

processors:
    active: true

console-reports:
    active: true
    exclude:
        - 'ProjectStatisticsReport'

# ===== Reglas para Android/Compose =====
style:
    MagicNumber:
        active: true
        ignorePropertyDeclaration: true
        ignoreCompanionObjectPropertyDeclaration: true
        ignoreAnnotation: true
        ignoreEnums: true
    UnusedPrivateMember:
        active: true   # <-- AQUÍ va esta regla

performance:
    SpreadOperator:
        active: true

exceptions:
    SwallowedException:
        active: true

potential-bugs:
    CastToNullableType:
        active: true

naming:
    FunctionNaming:
        active: true
        # Permitimos PascalCase en @Composable que devuelven Unit
        functionPattern: '[a-zA-Z][a-zA-Z0-9]*'
        ignoreAnnotated: ['Composable', 'Preview']
    TopLevelPropertyNaming:
        active: true
        constantPattern: '[A-Z][A-Za-z0-9]*'

complexity:
    LongMethod:
        active: true
        threshold: 80
    CyclomaticComplexMethod:
        active: true
        threshold: 15
    LongParameterList:
        active: true
        functionThreshold: 8
        ignoreDefaultParameters: true
    TooManyFunctions:
        active: true

# Si usas el plugin de coroutines, deja este bloque;
# si no, coméntalo o añade el plugin detekt-rules-coroutines en build.gradle.kts (raíz).
coroutines:
    GlobalCoroutineUsage:
        active: true
    InjectDispatcher:
        active: true
    RedundantSuspendModifier:
        active: true
    SleepInsteadOfDelay:
        active: true
    SuspendFunWithFlowReturnType:
        active: true

output-reports:
    active: true
